name: 'template-updater'
author: 'Sebastian Pekarek'
description: 'Updates a fork of a template repository by creating pull requests for changes'
inputs:
  token:
    description: 'GitHub private access token to be used'
    required: true
  bot-token:
    description: 'If the PRs are not to be created from a private token, the bot token must be specified here'
    required: false
  template:
    description: 'Template repository to be used (orga/repo/branch)'
    default: sebbo2002/js-template/typescript
    required: true
  assignees:
    description: 'Users that should be assigned to the pull request, split by comma'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: git-branch
  color: gray-dark
